name = "Abbie's Spectrum Pack"
author = "Abbie"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "655cee074d9c4a7581a216f027df9f727425d6af961d113a246ea400cfd7eb35"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
