name = "Abbie's Spectrum Pack"
author = "Abbie"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b9909779c79699f21a2fd0e78dbec2408f88274c8c7865c763ef262262717e4"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
