name = "Abbie's Spectrum Pack"
author = "Abbie"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a38be54bce2f82a36da45bc3b1793b2b95f10387b94268a06ce1f0b25acd12f4"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
