name = "Abbie's Spectrum Pack"
author = "Abbie"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1491da39070241c5327815a1eb0f70983d4c5f6afad85197a471fbccbef681f"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
