name = "Abbie's Spectrum Pack"
author = "Abbie"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12edbb4d8c3afcce85193acb6b48e82041b3b1f3a3a6478fafb63290442a594c"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
