name = "Abbie's Spectrum Pack"
author = "Abbie"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db34b6830bc65b75c091826e4ee9e63aef9d0c9127bfc3a8588855891d2f4d9a"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
