name = "Abbie's Spectrum Pack"
author = "Abbie"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04944fafdc4f9e3fbd46a2b6faec96e5d82b0156829deaf9aaf5e8f27432a262"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
