name = "Abbie's Spectrum Pack"
author = "Abbie"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c1b119038bafd3cd6e8666fe9c4d78cc2a7a92a99e311723f07e9d20a620b11"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
