name = "Abbie's Spectrum Pack"
author = "Abbie"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87fab9cb2640174d394fc2a541ffb34fa1a9272486c6f7e0da4335571b7f6ce7"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
