name = "Abbie's Spectrum Pack"
author = "Abbie"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75ea5a6737608957fbe8189fcf6c5fa51f8551a65f62be5a740e68802e1abb17"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
