name = "Abbie's Spectrum Pack"
author = "Abbie"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db9b38bd16f1595f8e9255fe4f753934b250dfad0de56cf2a37cf0f752da2efb"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
