name = "Abbie's Spectrum Pack"
author = "Abbie"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11dee351f02b69d56fea99fabc3fc2e1e91813a3aeb0e496e2683f6083933dbd"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
