name = "Abbie's Spectrum Pack"
author = "Abbie"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fb0467a9e0af54e3e6d8fe74e4fc47c7460224c2d7c0a5d77177754e9f2c657"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
