name = "Abbie's Spectrum Pack"
author = "Abbie"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3429acc4c91eb65b2f68f392a0f6a30e62680a1f9c090ae36ea08c5f90b11f4a"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
