name = "Abbie's Spectrum Pack"
author = "Abbie"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8bc03dea285eb95cd361deb0af9e58732e5a8a5bbf3b124103b1934ab937fb48"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
